### ISSUE TITLE
[bug]与xiaoyao-cvs-plugin的体力有冲突

### ISSUE THREAD

**Issue by liuzj288** [gxy12345/windoge-plugin#10]
windoge-plugin的体力关闭情况下，#体力模板列表依然唤出windoge-plugin的模板文件夹而不是xiaoyao-cvs-plugin的模板文件夹

**Comment by gxy12345** [comment]
已修复，可以验证一下，我这里因为没有使用xiaoyao-cvs-plugin的体力功能，所以未验证
