### ISSUE TITLE
兑换码收录貌似不是很完整

### ISSUE THREAD

**Issue by DivinationHW** [gxy12345/windoge-plugin#11]
NT8SU92DKFRZ
60原石5蓝经验书，国际服 11月2日出炉
WARBDRR9MCQ9
冒险家的经验*10 + 摩拉*10000 + 精锻用良矿*5 + 北地烟熏鸡*5 + 火火肉酱面*5 
注: HoYoLAB & Google Play & YouTube Premium 联合福利其一. 11月1日出炉

**Comment by DivinationHW** [comment]
均为国际服兑换码，近期（五天内）的

**Comment by gxy12345** [comment]
目前兑换码没有类似国服的官方API，数据来源都是资讯网站，现在使用的资讯网站已经算是比较及时的了，上述两个兑换码，我在11月2日晚上已经可以查询到了

**Comment by DivinationHW** [comment]
> 目前兑换码没有类似国服的官方API，数据来源都是资讯网站，现在使用的资讯网站已经算是比较及时的了，上述两个兑换码，我在11月2日晚上已经可以查询到了

![image](https://user-images.githubusercontent.com/107331343/199904377-5982688c-0340-40c1-9308-d42da0be3e75.png)
目前来看应该是服务器无法访问这个兑换码网站，然后插件没访问成功就回复了当前无可用兑换码，（这网站在我本地挂代理反而上不去，很奇怪），如果方便的话可以麻烦大佬考虑一下后续走config里国际服用的http代理链接，谢谢。

**Comment by DivinationHW** [comment]
搞定了已经，就不麻烦大佬写这个走代理了，已关闭问题，完美解决
