### ISSUE TITLE
【功能需求】有没有兴趣把妮可少年的深渊buff预测加进来？

### ISSUE THREAD

**Issue by liuzj288** [gxy12345/windoge-plugin#15]

**Comment by gxy12345** [comment]
是否有固定的发布站点？

**Comment by liuzj288** [comment]
> 是否有固定的发布站点？

首发是nga，不过我没有查看权限，Telegram有搬运
![image](https://user-images.githubusercontent.com/13833404/200285967-55ac8737-9143-4bf1-afb1-0f29fab22b5d.png)

**Comment by gxy12345** [comment]
目前这种没有固定帖子整理搬运的，很难通过机器人去自动拉取
