### ISSUE TITLE
在某些特殊环境下，因无法修改每个进程可开启的最大文件数（仅为1024），在执行”#导入便签背景图6“时会报错，随后bot卡死并重启

### ISSUE THREAD

**Issue by kissnavel** [gxy12345/windoge-plugin#16]
![Z8O} 7C91X5A~1YZVSAP%)C](https://user-images.githubusercontent.com/53962152/201534755-3cc88f71-ebfa-48f5-aea2-9d2fbb0774a0.png)
这时候需要手动将”resources/BJT-Template“文件夹内的Template2文件夹下所有内容复制至resources/dailyNote/Template文件夹内。
首先进入插件内的”resources/BJT-Template“文件夹，然后：
cp -Rf Template2/* /root/Yunzai-Bot/plugins/windoge-plugin/resources/dailyNote/Template/
上述插件地址自行替换。

**Comment by kissnavel** [comment]
> 我使用”#导入便签背景图6“并没有复现这个问题，产生问题前是否有其他操作?

没有过其他操作，起初认为有其他进程占用连接数，重启后重新操作仍然报错。

**Comment by kissnavel** [comment]
> > 我使用”#导入便签背景图6“并没有复现这个问题，产生问题前是否有其他操作?
> 
> 没有过其他操作，起初认为进程有打开其他文件占用数量限制，重启后重新操作仍然报错。虽然能手动复制，但是会导致用“便签”指令生成的模板偶尔无背景图和文字。1、2、3、4、5、7是正常的，目前暂时跳过了6的导入。

之前issue标题描述有误已修改。之前说到指令导入6报错，手动复制后会导致会导致用“便签”指令生成的模板偶尔无背景图和文字。经过测试，使用“#清空便签背景图”后重新使用”#导入便签背景图“导入1~7（6除外），然后进入resources/BJT-Template文件夹，手动将Template2文件夹下所有内容复制至/root/Yunzai-Bot/plugins/windoge-plugin/resources/dailyNote/Template/（地址自行替换）文件夹下，这样所有用“便签”指令生成的图皆正常。
经过查看，”#导入便签背景图“导入1~7（6除外）的内容为Template、Template3文件夹下的内容，”#导入便签背景图6“导入Template2文件夹下的内容。目前Template、Template3根目录下的文件夹数量均为69，Template2根目录下文件夹数量为150。如果”#导入便签背景图6“为同时复制Template2目录下所有文件，确实会超过1024的限制。建议将文件夹下内容拆分或进行导入的限制。不过这个不算是bug，这只是在某些特殊环境下无法修改环境配置引发的问题，几乎不会有人碰到。

**Comment by kissnavel** [comment]
> > 我使用”#导入便签背景图6“并没有复现这个问题，产生问题前是否有其他操作?
> 
> 没有过其他操作，起初认为进程有打开其他文件占用数量限制，重启后重新操作仍然报错。虽然能手动复制，但是会导致用“便签”指令生成的模板偶尔无背景图和文字。1、2、3、4、5、7是正常的，目前暂时跳过了6的导入。

之前issue标题描述有误已修改。之前说到指令导入6报错，手动复制后会导致会导致用“便签”指令生成的模板偶尔无背景图和文字。经过测试，使用“#清空便签背景图”后重新使用”#导入便签背景图“导入1~7（6除外），然后进入resources/BJT-Template文件夹，手动将Template2文件夹下所有内容复制至/root/Yunzai-Bot/plugins/windoge-plugin/resources/dailyNote/Template/（地址自行替换）文件夹下，这样所有用“便签”指令生成的图皆正常。
经过查看，”#导入便签背景图“导入1~7（6除外）的内容为Template、Template3文件夹下的内容，”#导入便签背景图6“导入Template2文件夹下的内容。目前Template、Template3根目录下的文件夹数量均为69，Template2根目录下文件夹数量为150。如果”#导入便签背景图6“为同时复制Template2目录下所有文件，确实会超过1024的限制。建议将文件夹下内容拆分或进行导入的限制。不过这个不算是bug，这只是在某些特殊环境下无法修改环境配置引发的问题，几乎不会有人碰到。

**Comment by kissnavel** [comment]
> > 我使用”#导入便签背景图6“并没有复现这个问题，产生问题前是否有其他操作?
> 
> 没有过其他操作，起初认为进程有打开其他文件占用数量限制，重启后重新操作仍然报错。虽然能手动复制，但是会导致用“便签”指令生成的模板偶尔无背景图和文字。1、2、3、4、5、7是正常的，目前暂时跳过了6的导入。

之前issue标题描述有误已修改。之前说到指令导入6报错，手动复制后会导致会导致用“便签”指令生成的模板偶尔无背景图和文字。经过测试，使用“#清空便签背景图”后重新使用”#导入便签背景图“导入1~7（6除外），然后进入resources/BJT-Template文件夹，手动将Template2文件夹下所有内容复制至/root/Yunzai-Bot/plugins/windoge-plugin/resources/dailyNote/Template/（地址自行替换）文件夹下，这样所有用“便签”指令生成的图皆正常。
经过查看，”#导入便签背景图“导入1~7（6除外）的内容为Template、Template3文件夹下的内容，”#导入便签背景图6“导入Template2文件夹下的内容。目前Template、Template3根目录下的文件夹数量均为69，Template2根目录下文件夹数量为150。如果”#导入便签背景图6“为同时复制Template2目录下所有文件，确实会超过1024的限制。建议将文件夹下内容拆分或进行导入的限制。不过这个不算是bug，这只是在某些特殊环境下无法修改环境配置引发的问题，几乎不会有人碰到。

**Comment by kissnavel** [comment]
之前issue标题描述有误已修改。之前说到指令导入6报错，手动复制后会导致会导致用“便签”指令生成的模板偶尔无背景图和文字。经过测试，使用“#清空便签背景图”后重新使用”#导入便签背景图“导入1~7（6除外），然后进入resources/BJT-Template文件夹，手动将Template2文件夹下所有内容复制至/root/Yunzai-Bot/plugins/windoge-plugin/resources/dailyNote/Template/（地址自行替换）文件夹下，这样所有用“便签”指令生成的图皆正常。
经过查看，”#导入便签背景图“导入1~7（6除外）的内容为Template、Template3文件夹下的内容，”#导入便签背景图6“导入Template2文件夹下的内容。目前Template、Template3根目录下的文件夹数量均为69，Template2根目录下文件夹数量为150。如果”#导入便签背景图6“为同时复制Template2目录下所有文件，确实会超过1024的限制。建议将文件夹下内容拆分或进行导入的限制。不过这个不算是bug，这只是在某些特殊环境下无法修改环境配置引发的问题，几乎不会有人碰到。

**Comment by kissnavel** [comment]
> > 我使用”#导入便签背景图6“并没有复现这个问题，产生问题前是否有其他操作?
> 
> 没有过其他操作，起初认为进程有打开其他文件占用数量限制，重启后重新操作仍然报错。虽然能手动复制，但是会导致用“便签”指令生成的模板偶尔无背景图和文字。1、2、3、4、5、7是正常的，目前暂时跳过了6的导入。

之前issue标题描述有误已修改。之前说到指令导入6报错，手动复制后会导致会导致用“便签”指令生成的模板偶尔无背景图和文字。经过测试，使用“#清空便签背景图”后重新使用”#导入便签背景图“导入1~7（6除外），然后进入resources/BJT-Template文件夹，手动将Template2文件夹下所有内容复制至/root/Yunzai-Bot/plugins/windoge-plugin/resources/dailyNote/Template/（地址自行替换）文件夹下，这样所有用“便签”指令生成的图皆正常。

**Comment by gxy12345** [comment]
1.对于too many open file报错，增加了并发控制，但本地为复现此问题，故无法验证是否已修复
2.便签背景图6中的模板背景无法显示问题，因为模板目录名含有空格，作为background无法读取，增加了对路径的URLencode操作

**Comment by kissnavel** [comment]
> 1.对于too many open file报错，增加了并发控制，但本地未复现此问题，故无法验证是否已修复 2.便签背景图6中的模板背景无法显示问题，因为模板目录名含有空格，作为background无法读取，增加了对路径的URLencode操作

![TS7G68{FEAP46UWK6ZTA$9I](https://user-images.githubusercontent.com/53962152/201959250-7f524068-f293-4031-85b4-de444598dc61.png)
1.仍然报错too many open files。2.手动复制便签背景图6，模板背景无法显示问题已修复。
报错问题不碍事，因为可手动复制解决导入问题。
