### ISSUE TITLE
bagpipe包一直安装不成功

### ISSUE THREAD

**Issue by liuzj288** [gxy12345/windoge-plugin#18]
![image](https://user-images.githubusercontent.com/13833404/202453405-7fe94557-d72d-49eb-b4d7-49d2d4864045.png)
![image](https://user-images.githubusercontent.com/13833404/202453797-2e9804aa-81dd-49e8-b9b4-c93637b85702.png)

**Comment by gxy12345** [comment]
已移除依赖
