### ISSUE TITLE
使用“#导入便签背景图1~7“均报错ws is not defined

### ISSUE THREAD

**Issue by kissnavel** [gxy12345/windoge-plugin#19]
![I5WO@A_SWOI{_ @30M(FFLD](https://user-images.githubusercontent.com/53962152/202771330-de187a2b-a82e-41a1-9406-4fa340b6e672.png)
bot回复”导入背景图完成“，实际并未导入，目前暂时以手动方式导入。

**Comment by gxy12345** [comment]
已修复
