### ISSUE TITLE
背景图大概率用原本默认的背景图

### ISSUE THREAD

**Issue by ABT98421** [gxy12345/windoge-plugin#22]
已经将仓库2导入template，里面有一百来个，但是使用一次#体力还是极大概率会用background里的模版，多次使用#体力才能抽出template里的模版

**Comment by gxy12345** [comment]
检查一下plugins/windoge-plugin/resources/dailyNote/template下面的目录，看下是否包含了模板.
另外本插件插件体力用的是`#便签`命令，#体力不会触发本插件的体力查询
