### ISSUE TITLE
这两个蹦蹦蹦的合集有没有简单方案实现？

### ISSUE THREAD

**Issue by liuzj288** [gxy12345/windoge-plugin#39]
蹦蹦蹦每周可用兑换码
https://www.miyoushe.com/bh3/collection/4492
可以一次把各帖兑换码都扒下来发出

版本乐土攻略
https://www.miyoushe.com/bh3/collection/1060106
问题是每个版本角色不同（不更新版本坐牢角色），似乎只能扒下来手动改名匹配

**Comment by gxy12345** [comment]
暂时不考虑做崩3相关的功能
