### ISSUE TITLE
汇率API请求失败

### ISSUE THREAD

**Issue by o02** [gxy12345/windoge-plugin#42]
已经通过#windoge设置汇率key c9d1de52e9aba8cd9da5**** 设置了，查询还是提示汇率API请求失败

**Comment by gxy12345** [comment]
先排查一下是不是网络问题，使用机器人所在的设备请求一下汇率接口(https://v6.exchangerate-api.com/v6/${api_key}/latest/CNY)看看能不能正常请求，实在不行就把这个加到梯子的代理里面

**Comment by o02** [comment]
[root@VM-12-6-centos ~]# curl https://v6.exchangerate-api.com/v6/${api_key}/latest/CNY
{"result":"error","documentation":"https://www.exchangerate-api.com/docs","terms-of-use":"https://www.exchangerate-api.com/terms","error-type":"invalid-key"}
所在的设备，测试能正常连接到汇率接口的。可能是支持库的原因，之前用
pnpm install --filter=windoge-plugin
安装了，目前能正常使用其它功能的，用
npm install date-format
安装的话，最后会出错。安装日志太长，不折腾这功能了，其它功能正常使用不管它了。
