### ISSUE TITLE
【功能需求】祈鸢ya 这个采集路线能不能加进来，调用截图

### ISSUE THREAD

**Issue by liuzj288** [gxy12345/windoge-plugin#44]
合集：https://www.miyoushe.com/ys/collection/1845635
命令示范：#圣金虫路线
返回页面截图：

![image](https://user-images.githubusercontent.com/13833404/224005852-b7d40bf6-717f-499a-8e92-588e04748e87.png)

**Comment by gxy12345** [comment]
有对应的合集吗？这样好弄一点

**Comment by liuzj288** [comment]
> 有对应的合集吗？这样好弄一点

忘说了，我看她好像打算补完采集物
 https://www.miyoushe.com/ys/collection/1845635

**Comment by liuzj288** [comment]
这个collection_id支不支持添加多个呢
![image](https://user-images.githubusercontent.com/13833404/225291983-7b436831-20f8-4d34-a89f-e1f9aeb3fa90.png)

**Comment by gxy12345** [comment]
可以，我之后加一下，根据优先级搜索所以collection

**Comment by liuzj288** [comment]
> 可以，我之后加一下，根据优先级搜索所以collection

她这个邀约攻略我觉得也可以加进来，一直还在更新

**Comment by gxy12345** [comment]
我看邀约攻略折叠了很多内容，效果会不太好，所以不做了
