### ISSUE TITLE
很抱歉是关于其他插件的问题

### ISSUE THREAD

**Issue by DivinationHW** [gxy12345/windoge-plugin#5]
![0~B7{W ~4%`A`IG3QL(9LI5](https://user-images.githubusercontent.com/107331343/192325769-ff8e57dd-6832-4d5a-895e-55048f78786e.png)
[xiaoyao-cvs-plugin](https://github.com/ctrlcvs/xiaoyao-cvs-plugin)
听说您在喵喵插件群，但不知是具体哪位，所以在此留言，打扰了。
目前上述插件链接xiaoyao-cvs-plugin正在适配国际服的一部分功能（通过stoken更新cookie和抽卡记录），但因为salt卡在了最后一步，具体技术细节很抱歉我本人不太懂，贴上聊天记录询问。
![image](https://user-images.githubusercontent.com/107331343/192326476-5ca1a933-0fa8-4cd5-9f9b-b22fbee07c07.png)
![image](https://user-images.githubusercontent.com/107331343/192326503-efc543a9-59e4-4d87-bf6d-f487bcf3bc01.png)
此插件开发者和您一样，在喵喵插件群，为红框这位：
![image](https://user-images.githubusercontent.com/107331343/192326913-62d9d02c-cad8-4899-aeb4-8cae6208c6c8.png)
您对此问题是否有什么解决办法，若有，则麻烦两位佬私下沟通一下。
最后感谢您对国际服机器人项目的贡献。

**Comment by gxy12345** [comment]
不太清楚这个DS的使用场景是什么，看到截图中没有用过一个最早的salt，不妨试一下
```
    "salt": "h8w582wxwgqvahcdkpvdhbh2w9casgfl",
    "x-rpc-app_version": "2.3.0",
    "x-rpc-client_type": 5,
    "User-Agent": " miHoYoBBS/2.3.0",
```
