### ISSUE TITLE
发送#未复刻角色还是出错，是哪里需要在修改下吗

### ISSUE THREAD

**Issue by EOP-Muzzy** [gxy12345/windoge-plugin#58]
![image](https://user-images.githubusercontent.com/77168105/228394414-e849905a-d587-4252-bfee-cb6141964a6a.png)

**Comment by gxy12345** [comment]
梯子可以正常访问GitHub吗？试一下这个文件能不能正常访问https://raw.githubusercontent.com/gxy12345/windoge-plugin/main/config/banner/character.json
不能就试一下其他的数据源 #windoge设置卡池数据源3
