### ISSUE TITLE
素材汇总图查询失败

### ISSUE THREAD

**Issue by CUZNIL** [gxy12345/windoge-plugin#59]
![}MMS{ OSTA9UFZ@SMN`PR%1](https://user-images.githubusercontent.com/76582404/228740328-f94a4eea-1f49-4f10-8095-667e1a0b6698.png)

如图所示，#天赋素材 #武器素材 #周本素材 均提示查询失败

未复刻角色可以正常使用

日志和本地数据如下图

![8T9% 2C1%H()F59 _1_%KWS](https://user-images.githubusercontent.com/76582404/228740530-b50abc4a-276f-433b-a0fa-3c854bcd4827.jpg)

![(@{N3_H5AO)DVR`NT9JVQJ2](https://user-images.githubusercontent.com/76582404/228740543-40547a18-08af-4fa4-b76c-7c73307da59d.jpg)

已尝试重装重启和开关vbn 均无法解决

**Comment by gxy12345** [comment]
进入redis，清空以下缓存
windoge:material:normal_talent
windoge:material:week_talent
windoge:material:weapon
然后重新触发命令下载图片

**Comment by gxy12345** [comment]
理论上不应该出现这种情况，不过可以考虑加一个手动清空缓存的命令
