### ISSUE TITLE
希望能把采集路线指令的优先级调低

### ISSUE THREAD

**Issue by Zhuazizizi** [gxy12345/windoge-plugin#61]
在使用#晶碟采集路线时提示暂未找到指定素材路线攻略，转而使用本体的#米游社晶碟采集路线时被抢了指令，所以希望可以改低一下优先级。（其实我换个字眼搜索帖子就行，所以不改也许也没啥事。）

**Comment by gxy12345** [comment]
#62 已解决，如果命令带有米游社则不会拦截
