### ISSUE TITLE
原石预估报错

### ISSUE THREAD

**Issue by 1353798039** [gxy12345/windoge-plugin#72]
![捕获](https://github.com/gxy12345/windoge-plugin/assets/108866283/18a99a38-1aca-4519-95e0-1c4ae0b42d94)

**Comment by gxy12345** [comment]
无法复现这个问题，但是尝试增加了异常处理

commit 9a7aa8a191079c50c17d94e85112a98d2afd8ff5

**Comment by 1353798039** [comment]
好像可以了
